### ISSUE TITLE
Can't PR against the Repo due to permission (version update change)

### ISSUE THREAD

**Issue by angrygoats** [pragmaticivan/logglix#4]
Hi!

For some strange reason I can't PR against this repo to make changes. I keep getting permission problems. 

The change I wanted to make is really simple:

1. HTTPoison can be upgraded to `~> 0.13.0` so we don't have to unlock the dependency to get it to work along side the current version of HTTPoison
2. The version specified in the README.md (`~> 0.0.1`) can be updated to `~> 0.1.0`

Thank you!

**Comment by pragmaticivan** [comment]
Thanks @angrygoats I will take a look

**Comment by pragmaticivan** [comment]
Done @angrygoats ! thanks! It's 1.0.0 now.
